"""Generates a starter README.md for a book output.

Running this pipeline against a PDF produces a project of its own -- a repo
that hosts one specific book's generated site plus the pipeline artifacts
behind it. That project deserves a README that actually describes *that
book* (title, author, how far processing has gotten, how to build and view
it), not a copy-pasted description of the tool.

Unlike PROGRESS.md, this is not regenerated on every run: it's a starting
point, written once from `work/triage.json`, meant to be hand-edited
afterward (fill in licensing specifics, project notes, etc.). Re-run with
--force if you want to reset it and lose those edits.

Run: bookery readme
"""

from __future__ import annotations

import json
from pathlib import Path

from . import config, status


def render(triage: dict) -> str:
    source = triage.get("source", {})
    title = source.get("title") or "This Book"
    author = source.get("author")
    byline = f" by {author}" if author else ""

    progress_line = "not yet processed"
    if config.REPORTS.exists() and any(config.REPORTS.glob("ch*.json")):
        stats = status.summary(triage)
        if stats["chapters_total"]:
            progress_line = f"{stats['chapters_green']} of {stats['chapters_total']} chapters green"

    return "\n".join(
        [
            f"# {title}",
            "",
            f"A fidelity-checked Docusaurus build of *{title}*{byline}, generated by",
            "[bookery](https://github.com/bug-breeder/bookery): every chapter is",
            "checked against the source PDF by an eight-gate verification harness",
            "(text coverage, numeric fidelity, structural counts, assets, math,",
            "cross-references, site build, visual adjudication) before it counts",
            "as done.",
            "",
            f"**Status:** {progress_line}. See [PROGRESS.md](./PROGRESS.md) for the",
            "full per-chapter breakdown (regenerated by `bookery status`).",
            "",
            "## Running it",
            "",
            "```bash",
            "uv sync --extra dev",
            "",
            "uv run bookery build --pdf path/to/source.pdf --all   # process every chapter",
            "uv run bookery verify --all --build                   # re-check everything",
            "uv run bookery view                                   # open it in a browser",
            "```",
            "",
            "`bookery view` installs the site's JS dependencies on first run, then",
            "starts a local dev server. Pass `--build` to it for a production build",
            "served as static files instead. Run `uv run bookery --help` for every",
            "other command (`extract`, `reconcile`, `assets`, `emit`, ... -- each",
            "stage can be re-run on its own).",
            "",
            "## Licensing",
            "",
            "> **Fill this in before sharing this build anywhere.** Check the rights",
            "> terms of the source PDF -- this generator does not know them and",
            "> carries no assumption from one book to the next. If the source is",
            "> copyrighted and you don't hold redistribution rights, keep this",
            "> repository private and don't deploy the built site publicly.",
        ]
    ) + "\n"


def write(force: bool = False) -> Path | None:
    path = config.ROOT / "README.md"
    if path.exists() and not force:
        print(f"{path.name} already exists -- pass --force to overwrite it.")
        return None
    if not config.TRIAGE_JSON.exists():
        raise SystemExit(
            "work/triage.json does not exist yet -- run `bookery acquire "
            "--pdf <file>` first."
        )
    triage = json.loads(config.TRIAGE_JSON.read_text())
    path.write_text(render(triage))
    print(f"wrote {path.name}")
    return path


if __name__ == "__main__":
    write()
