"""Regenerates PROGRESS.md from the pipeline's own artifacts.

Progress is derived, never asserted. Every value here is read back from
triage.json, the stage outputs on disk, and the gate reports, so a chapter
cannot be recorded as done while its gates disagree. Hand-maintained status
files drift the moment someone forgets to update them; this one cannot.

Design intent lives in ARCHITECTURE.md and is written by hand. Run state
lives here and is generated. The two must not be mixed.

Run:  python -m pipeline.status   (or: bookery status)
"""

from __future__ import annotations

import json
from dataclasses import dataclass

from . import config

GATE_NAMES = (
    "text_coverage",
    "numeric_fidelity",
    "structural_counts",
    "assets",
    "math",
    "xrefs",
    "build",
    "visual",
)

PASSING = {"PASS", "REVIEWED"}


@dataclass
class ChapterState:
    number: int
    title: str
    printed: str
    extracted: bool
    reconciled: bool
    has_assets: bool
    emitted: bool
    gates_passed: int
    gates_total: int
    status: str
    pages: int

    @property
    def is_green(self) -> bool:
        return self.status == "green"


def _chapter_state(chapter: dict, assets: dict) -> ChapterState:
    number = chapter["number"]
    cid = config.chapter_id(number)

    marker = (config.EXTRACT_DIR / "marker" / f"{cid}.json").exists()
    docling = (config.EXTRACT_DIR / "docling" / f"{cid}.json").exists()
    reconciled = (config.RECONCILE_DIR / f"{cid}.json").exists()
    # Presence of the key means stage3 ran for this chapter, even if it found
    # zero figures (e.g. a preface). An empty list is a real, checked result,
    # not the same thing as the stage never having run.
    has_assets = cid in assets
    emitted = bool(sorted(config.DOCS.rglob(f"{number:02d}-*.md"))) if config.DOCS.exists() else False

    report_path = config.REPORTS / f"{cid}.json"
    passed = 0
    status = "not started"
    if report_path.exists():
        report = json.loads(report_path.read_text())
        gates = report.get("gates", {})
        passed = sum(1 for name in GATE_NAMES if gates.get(name, {}).get("status") in PASSING)
        if passed == len(GATE_NAMES):
            status = "green"
        elif any(g.get("status") == "FAIL" for g in gates.values()):
            status = "failing"
        else:
            status = "in progress"
    elif reconciled or marker:
        status = "in progress"

    return ChapterState(
        number=number,
        title=chapter["title"],
        printed=config.printed_page_range(chapter),
        extracted=marker and docling,
        reconciled=reconciled,
        has_assets=has_assets,
        emitted=emitted,
        gates_passed=passed,
        gates_total=len(GATE_NAMES),
        status=status,
        pages=chapter["pdf_page_end"] - chapter["pdf_page"] + 1,
    )


def chapter_states(triage: dict) -> dict[int, ChapterState]:
    bm = triage["boundary_map"]
    assets = json.loads(config.ASSETS_JSON.read_text()) if config.ASSETS_JSON.exists() else {}
    return {c["number"]: _chapter_state(c, assets) for c in bm["chapters"]}


def summary(triage: dict) -> dict:
    """Chapter/page green counts, cheap enough to call from `bookery readme`."""
    states = chapter_states(triage)
    green = [s for s in states.values() if s.is_green]
    total_pages = sum(s.pages for s in states.values())
    green_pages = sum(s.pages for s in green)
    return {
        "chapters_green": len(green),
        "chapters_total": len(states),
        "pages_green": green_pages,
        "pages_total": total_pages,
    }


def build() -> str:
    triage = json.loads(config.TRIAGE_JSON.read_text())
    states = chapter_states(triage)
    green = [s for s in states.values() if s.is_green]
    total_pages = sum(s.pages for s in states.values())
    green_pages = sum(s.pages for s in green)

    bibliography = 0
    bib_path = config.DOCS / "bibliography.md"
    if bib_path.exists():
        import re

        bibliography = len(re.findall(r"^<a id=\"ref-\d+\">", bib_path.read_text(), re.M))

    rows: list[str] = [
        "# Progress",
        "",
        "Generated by `bookery status` (`python -m pipeline.status`). Do not edit",
        "by hand: every value is read back from the pipeline's artifacts and gate",
        "reports, so a chapter cannot be recorded as done while its gates",
        "disagree. Design intent and conventions are in ARCHITECTURE.md.",
        "",
        f"- Chapters green: **{len(green)} of {len(states)}**",
    ]
    if total_pages:
        rows.append(
            f"- Chapter pages green: **{green_pages} of {total_pages}** "
            f"({green_pages / total_pages:.1%})"
        )
    if bibliography:
        rows.append(f"- Bibliography entries: {bibliography}")

    rows += [
        "",
        "A chapter is *green* only when all eight gates pass. `visual` reports",
        "REVIEWED once every flagged page has an adjudication verdict on record.",
        "",
        "## Chapters",
        "",
        "Stage columns are `x` when that stage's artifact exists on disk.",
        "",
        "| Ch | Title | Printed pp. | Extract | Reconcile | Assets | Emit | Gates | Status |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for number in sorted(states):
        s = states[number]
        mark = lambda flag: "x" if flag else " "  # noqa: E731
        gates = f"{s.gates_passed}/{s.gates_total}" if s.gates_passed else "-"
        rows.append(
            f"| {s.number} | {s.title} | {s.printed} | {mark(s.extracted)} | "
            f"{mark(s.reconciled)} | {mark(s.has_assets)} | {mark(s.emitted)} | "
            f"{gates} | {s.status} |"
        )

    outstanding: list[str] = []
    for path in sorted(config.REPORTS.glob("ch*.json")):
        report = json.loads(path.read_text())
        for item in report.get("review_queue") or []:
            outstanding.append(
                f"- Chapter {report['chapter']}: {item.get('kind')} "
                f"{item.get('gate') or item.get('page') or ''}".rstrip()
            )

    rows += ["", "## Outstanding review items", ""]
    rows += outstanding or ["None. Every processed chapter is fully adjudicated."]

    return "\n".join(rows) + "\n"


def write() -> None:
    path = config.ROOT / "PROGRESS.md"
    path.write_text(build())
    print(f"wrote {path.name}")


if __name__ == "__main__":
    write()
