// Generated by pipeline/stage4_emit.py from work/triage.json.
// Do not edit by hand: regenerate with `python -m pipeline.stage4_emit`.
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  book: [
    'index',
    '00-preface',
    '01-overview',
    {
      type: 'category',
      label: 'I. Graph Theory and Social Networks',
      collapsed: false,
      items: [
        'part1-graph-theory-and-social-networks/02-graphs',
        'part1-graph-theory-and-social-networks/03-strong-and-weak-ties',
        'part1-graph-theory-and-social-networks/04-networks-in-their-surrounding-contexts',
        'part1-graph-theory-and-social-networks/05-positive-and-negative-relationships',
      ],
    },
    {
      type: 'category',
      label: 'II. Game Theory',
      collapsed: false,
      items: [
        'part2-game-theory/06-games',
        'part2-game-theory/07-evolutionary-game-theory',
        'part2-game-theory/08-modeling-network-traffic-using-game-theory',
        'part2-game-theory/09-auctions',
      ],
    },
    {
      type: 'category',
      label: 'III. Markets and Strategic Interaction in Networks',
      collapsed: false,
      items: [
        'part3-markets-and-strategic-interaction-in-networks/10-matching-markets',
        'part3-markets-and-strategic-interaction-in-networks/11-network-models-of-markets-with-intermediaries',
        'part3-markets-and-strategic-interaction-in-networks/12-bargaining-and-power-in-networks',
      ],
    },
    {
      type: 'category',
      label: 'IV. Information Networks and the World Wide Web',
      collapsed: false,
      items: [
        'part4-information-networks-and-the-world-wide-web/13-the-structure-of-the-web',
        'part4-information-networks-and-the-world-wide-web/14-link-analysis-and-web-search',
        'part4-information-networks-and-the-world-wide-web/15-sponsored-search-markets',
      ],
    },
    {
      type: 'category',
      label: 'V. Network Dynamics: Population Models',
      collapsed: false,
      items: [
        'part5-network-dynamics-population-models/16-information-cascades',
        'part5-network-dynamics-population-models/17-network-effects',
        'part5-network-dynamics-population-models/18-power-laws-and-rich-get-richer-phenomena',
      ],
    },
    {
      type: 'category',
      label: 'VI. Network Dynamics: Structural Models',
      collapsed: false,
      items: [
        'part6-network-dynamics-structural-models/19-cascading-behavior-in-networks',
        'part6-network-dynamics-structural-models/20-the-small-world-phenomenon',
        'part6-network-dynamics-structural-models/21-epidemics',
      ],
    },
    {
      type: 'category',
      label: 'VII. Institutions and Aggregate Behavior',
      collapsed: false,
      items: [
        'part7-institutions-and-aggregate-behavior/22-markets-and-information',
        'part7-institutions-and-aggregate-behavior/23-voting',
        'part7-institutions-and-aggregate-behavior/24-property-rights',
      ],
    },
    'bibliography',
  ],
};

export default sidebars;
