// Placeholder. Regenerated by `pipeline/stage4_emit.py` (`bookery emit`)
// from whatever chapters you've processed -- this file is overwritten on
// every emit run and should not be hand-edited.
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  book: ['index'],
};

export default sidebars;
